name: Testing brianlmoon/net_gearman

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '8.0'
            phpunit-versions: 9
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Composer Install
      uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php-versions }}

    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        php_extensions: "pcov yaml"
        version: "9.6"
        php_version: ${{ matrix.php-versions }}

    - name: Run Phan
      uses: k1LoW/phan-action@v0
